openapi: 3.0.0
info:
  title: Words API
  version: 1.0.0
servers:
  - url: /
paths:
  /words/{category}:
    get:
      parameters:
        - name: category
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Returns a list of words for the given category
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The unique identifier for the word
                    word:
                      type: string
                      description: The word text
                    category_id:
                      type: integer
                      description: The category identifier for the word